# Generated by Django 4.1.7 on 2023-02-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('temperature_1_day', models.FloatField(null=True)),
                ('temperature_2_day', models.FloatField(null=True)),
                ('temperature_3_day', models.FloatField(null=True)),
                ('temperature_7_day', models.FloatField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pog.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pog.weathersource')),
            ],
            options={
                'unique_together': {('city', 'source', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('temperature_1_day', models.FloatField(null=True)),
                ('temperature_2_day', models.FloatField(null=True)),
                ('temperature_3_day', models.FloatField(null=True)),
                ('temperature_7_day', models.FloatField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pog.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pog.weathersource')),
            ],
            options={
                'unique_together': {('city', 'source', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BestWeatherSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pog.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pog.weathersource')),
            ],
            options={
                'unique_together': {('city', 'source')},
            },
        ),
    ]
