# Generated by Django 4.1.7 on 2023-02-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pog', '0002_weathersource_remove_city_population_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='interia_site',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='onet_site',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
