# Generated by Django 4.1.7 on 2023-02-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pog', '0003_city_interia_site_city_onet_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherhistory',
            old_name='temperature',
            new_name='temp_max',
        ),
        migrations.AlterUniqueTogether(
            name='weatherhistory',
            unique_together={('city', 'date')},
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='temp_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='source',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='temperature_1_day',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='temperature_2_day',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='temperature_3_day',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='temperature_7_day',
        ),
    ]
